folio-org/mod-patron-blocks

.editorconfig
.gitignore
.gitmodules
CONTRIBUTING.md
LICENSE
NEWS.md
descriptors/DeploymentDescriptor-template.json
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/resources/log4j.properties

Create initial mod-patron-blocks implementation.
Resolves [MODPATBLK-2](https://issues.folio.org/browse/MODPATBLK-2)

MODPATBLK-2 create initial mod-patron-blocks implementation

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/main/resources/MessagingDescriptor.json
src/test/java/org/folio/rest/impl/APITests.java
src/test/java/org/folio/rest/impl/TenantRefAPITest.java
src/test/java/org/folio/rest/utils/OkapiClient.java

Subscribe the module to events published by `mod-circulation` and `mod-feesfines`.
Resovles [MODPATBLK-4](https://issues.folio.org/browse/MODPATBLK-4)

[MODPATBLK-4] Subscribe to circulation and fee/fine events

---

README.md

Added the required license statement.
Please add other stuff in due course, e.g. link to issue tracker
https://dev.folio.org/guidelines/create-new-repo/

FOLIO-360 Add license statement

---

ramls/events/item-checked-in.json
ramls/events/loan-due-date-changed.json
ramls/userSummary.json
src/main/java/org/folio/domain/EventType.java
src/main/java/org/folio/rest/handlers/LoanDueDateChangedEventHandler.java
src/main/java/org/folio/rest/impl/EventHandlersAPI.java
src/test/java/org/folio/rest/handlers/LoanDueDateChangedEventHandlerTest.java
src/test/java/org/folio/rest/impl/EventHandlersAPITest.java

Create handler for LOAN_DUE_DATE_CHANGED events.
Resolves [MODPATBLK-14](https://issues.folio.org/browse/MODPATBLK-14).

[MODPATBLK-14] Handle LOAN_DUE_DATE_CHANGED events

---

ramls/events/fee-fine-balance-changed.json
ramls/userSummary.json
src/main/java/org/folio/domain/Condition.java
src/main/java/org/folio/domain/FeeFineType.java
src/main/java/org/folio/repository/UserSummaryRepository.java
src/main/java/org/folio/rest/handlers/EventHandler.java
src/main/java/org/folio/rest/handlers/FeeFineBalanceChangedEventHandler.java
src/main/java/org/folio/rest/handlers/ItemCheckedOutEventHandler.java
src/main/java/org/folio/rest/handlers/ItemDeclaredLostEventHandler.java
src/test/java/org/folio/repository/UserSummaryRepositoryTest.java
src/test/java/org/folio/rest/handlers/EventHandlerTestBase.java
src/test/java/org/folio/rest/handlers/FeeFineBalanceChangedEventHandlerTest.java
src/test/java/org/folio/rest/handlers/ItemCheckedInHandlerTest.java
src/test/java/org/folio/rest/handlers/ItemCheckedOutEventHandlerTest.java
src/test/java/org/folio/rest/handlers/ItemDeclaredLostEventHandlerTest.java
src/test/java/org/folio/rest/handlers/LoanDueDateChangedEventHandlerTest.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java

Resolves [MODPATBLK-21](https://issues.folio.org/browse/MODPATBLK-21)

[MODPATBLK-21] Delete open loan from user summary when last related lost item fee is closed

---

NEWS.md
pom.xml
ramls/user.json
src/test/java/org/folio/rest/client/UsersClientTest.java

Q2-2020/Goldenrod bugfix release for [MODPATBLK-30](https://issues.folio.org/browse/MODPATBLK-30).
Resolves [MODPATBLK-31](https://issues.folio.org/browse/MODPATBLK-31).

Bugfix release 1.0.2

---

pom.xml

Resolves [MODPATBLK-36](https://issues.folio.org/browse/MODPATBLK-36).

MODPATBLK-36 Update to RMB v30.0.3

---

src/main/resources/templates/db_scripts/remove-user_summary-v1.0.4-unnecessary-fields.sql
src/main/resources/templates/db_scripts/schema.json

Creates migration script for removing "numberOfLostItems" and "outstandingFeeFineBalance" fields from user_summary DB table.
Resolves: [MODPATBLK-36](https://issues.folio.org/browse/MODPATBLK-36)

MODPATBLK-36 Remove unnecessary fields from DB

---

descriptors/ModuleDescriptor-template.json
ramls/eventHandlers.raml
ramls/events/item-claimed-returned.json
ramls/userSummary.json
src/main/java/org/folio/domain/ActionBlocks.java
src/main/java/org/folio/domain/EventType.java
src/main/java/org/folio/rest/handlers/ItemClaimedReturnedEventHandler.java
src/main/java/org/folio/rest/impl/EventHandlersAPI.java
src/main/resources/MessagingDescriptor.json
src/test/java/org/folio/domain/ActionBlocksTest.java
src/test/java/org/folio/rest/handlers/ItemClaimedReturnedEventHandlerTest.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java
src/test/java/org/folio/rest/impl/EventHandlersAPITest.java
src/test/java/org/folio/rest/utils/EntityBuilder.java

Resolves [MODPATBLK-8](https://issues.folio.org/browse/MODPATBLK-8).

[MODPATBLK-8] Exclude claim returned items from automated patron block limits

---

Dockerfile
Jenkinsfile
pom.xml

- upgrade to jdk 11;
- upgrade RMB to 31.0.2
Resolves: [MODPATBLK-50](https://issues.folio.org/browse/MODPATBLK-50)

MODPATBLK-50 upgrade RMB to 31.0.2 and JDK11

---

src/main/java/org/folio/service/FeesFinesEventsGenerationService.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

Resolves [MODPATBLK-65](https://issues.folio.org/browse/MODPATBLK-65)

[MODPATBLK-65] Fix FEE_FINE_BALANCE_CHANGED event generation

---

pom.xml

Resolves [MODPATBLK-63](https://issues.folio.org/browse/MODPATBLK-63)

[MODPATBLK-63] Update RMB to v31.1.5, update Vert.x to v3.9.4

---

descriptors/DeploymentDescriptor-template.json
pom.xml
src/main/java/org/folio/repository/BaseRepository.java
src/main/java/org/folio/repository/EventRepository.java
src/main/java/org/folio/rest/impl/PatronBlockConditionsAPI.java
src/main/java/org/folio/service/LoanEventsGenerationService.java
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/EventHandlersAPITest.java
src/test/java/org/folio/rest/impl/PatronBlockConditionsAPITest.java
src/test/java/org/folio/rest/utils/PomUtils.java

[MODPATBLK-86](https://issues.folio.org/browse/MODPATBLK-86)
RMB upgrade

MODPATBLK-86 Upgrade to RMB v33.0.0

---

pom.xml

Resolves [MODPATBLK-89](https://issues.folio.org/browse/MODPATBLK-89).

[MODPATBLK-89] Upgrade mod-pubsub-client to v2.3.0

---

NEWS.md
pom.xml

Resolves: [MODPATBLK-88](https://issues.folio.org/browse/MODPATBLK-88)

MODPATBLK-88 Release 1.3.0

---

NEWS.md
pom.xml
src/main/java/org/folio/rest/impl/PatronBlockLimitsAPI.java
src/test/java/org/folio/rest/impl/PatronBlockLimitsAPITest.java
src/test/resources/patron-block-limits/limit_max_outstanding_feefine_balance_limit_out_of_range.json

Resolves: [MODPATBLK-96](https://issues.folio.org/browse/MODPATBLK-96)

MODPATBLK-96 Release 1.3.1

---

src/main/java/org/folio/rest/client/BulkDownloadClient.java
src/main/java/org/folio/rest/client/OkapiClient.java

Decrease quantity of logs lines produced by fetchById() method of the module
Moved new lines available in json response body and structured data within one line
https://issues.folio.org/browse/MODPATBLK-104

MODPATBLK-104 New lines removal from logs

---

pom.xml

In the scope of the task on module upgrade, proper actions were fulfilled following instructions to update RMB
•	Updated RMB version
https://issues.folio.org/browse/MODPATBLK-113
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md

MODPATBLK-113 Update RMB to v33.2.4

---

src/main/java/org/folio/service/EventService.java
src/main/java/org/folio/service/PatronBlocksService.java
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java
src/test/java/org/folio/rest/impl/EventHandlersAPITest.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java
src/test/java/org/folio/rest/utils/EventClient.java

[MODPATBLK-117](https://issues.folio.org/browse/MODPATBLK-117)
_Stop automated patron blocks calculation when there are no blocks_

MODPATBLK-117: Stop automated patron blocks calculation when there are no blocks

---

NEWS.md
pom.xml
src/main/java/org/folio/repository/BaseRepository.java
src/main/java/org/folio/repository/UserSummaryRepository.java
src/main/java/org/folio/service/SynchronizationJobService.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

https://issues.folio.org/browse/MODPATBLK-131

[MODDPATBLK-131] Release 1.4.2

---

NEWS.md
pom.xml
src/main/java/org/folio/repository/BaseRepository.java
src/main/java/org/folio/repository/UserSummaryRepository.java
src/main/java/org/folio/service/SynchronizationJobService.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

https://issues.folio.org/browse/MODPATBLK-132

[MODPATBLK-132] Release 1.5.3

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODPATBLK-146

MODPATBLK-146: Release 1.7.0

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j.properties
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

https://issues.folio.org/browse/MODPATBLK-150

MODPATBLK-150: Logging improvement - check log4j configuration

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODPATBLK-153

MODPATBLK-153: Release mod-patron-blocks v1.6.1

---

NEWS.md
pom.xml

Resolves: [MODPATBLK-156](https://issues.folio.org/browse/MODPATBLK-156) Release mod-patron-blocks 1.8.0
[BE module release procedure](https://docs.google.com/document/d/1044I8jehoiu243BQ8GIUWCprdIYiDLqBEu5BZMjmCs0/edit)

MODPATBLK-156: Release 1.8.0

---

NEWS.md
pom.xml

Resolves: [MODPATBLK-168](https://issues.folio.org/browse/MODPATBLK-168)

[MODPATBLK-168] Release v1.9.0

---

pom.xml
src/main/java/org/folio/util/UuidHelper.java
src/test/java/org/folio/util/UuidHelperTest.java

Resolves: [MODPATBLK-174](https://folio-org.atlassian.net/browse/MODPATBLK-174)

MODPATBLK-174 Upgrade RMB, Vertx

---

NEWS.md
pom.xml

Resolves: [MODPATBLK-176](https://folio-org.atlassian.net/browse/MODPATBLK-176)

[MODPATBLK-176] Release 1.10.0

---

descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODPATBLK-182
- changed all permission with starting patron-blocks. 
- removed pubsub.event.post permission, introduced new instead

[MODPATBLK-182] - Review and cleanup Module Descriptors for mod-patron-blocks

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODPATBLK-188

Bugfix release 1.11.1

---

.github/workflows/postgres.yml
Dockerfile
Jenkinsfile
pom.xml

https://folio-org.atlassian.net/browse/MODPATRON-223
- updated depdendencies
- fixed compiled erros

[MODPATBLK-193] - Update to java 21

---

NEWS.md
pom.xml

Resolves: [MODPATBLK-194](https://folio-org.atlassian.net/browse/MODPATBLK-194)

Release 1.12.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Resolves: [MODPATBLK-197](https://folio-org.atlassian.net/browse/MODPATBLK-197)

MODPATBLK-197 Release 1.11.2

---

NEWS.md
pom.xml
ramls/events/fee-fine-balance-changed.json
ramls/events/item-aged-to-lost.json
ramls/events/item-checked-in.json
ramls/events/item-checked-out.json
ramls/events/item-claimed-returned.json
ramls/events/item-declared-lost.json
ramls/events/loan-closed.json
ramls/events/loan-due-date-changed.json
ramls/loan.json
ramls/period.json
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

https://folio-org.atlassian.net/browse/MODPATBLK-200
_How does this change fulfill the purpose?_

Bugfix release 1.11.3 (Ramsons CSP #2)

---

NEWS.md
pom.xml
ramls/events/fee-fine-balance-changed.json
ramls/events/item-aged-to-lost.json
ramls/events/item-checked-in.json
ramls/events/item-checked-out.json
ramls/events/item-claimed-returned.json
ramls/events/item-declared-lost.json
ramls/events/loan-closed.json
ramls/events/loan-due-date-changed.json
ramls/loan.json
ramls/period.json
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

[MODPATBLK-201](https://folio-org.atlassian.net/browse/MODPATBLK-201)

Bugfix release 1.12.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/service/SynchronizationJobService.java
src/test/java/org/folio/service/SynchronizationJobServiceTest.java

https://folio-org.atlassian.net/browse/MODPATBLK-213
_How does this change fulfill the purpose?_

Bugfix release v1.12.2 (Ramsons CSP)
