pom.xml
src/main/java/org/folio/patronblocks/repository/UserSummaryRepositoryImpl.java
src/test/java/org/folio/patronblocks/repository/UserSummaryRepositoryImplTest.java

- Update to RMB v30
- Update vertx to 3.9.0
- Do all related changes according to RMB upgrading notes
Resolves: [MODPATBLK-10](https://issues.folio.org/browse/MODPATBLK-10)

MODPATBLK-10 update RMB and vertx version

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/main/resources/MessagingDescriptor.json
src/test/java/org/folio/rest/impl/TenantRefAPITest.java

Resolves [MODPATBLK-16](https://issues.folio.org/browse/MODPATBLK-16).
Implements a workaround for [MODPUBSUB-90](https://issues.folio.org/browse/MODPUBSUB-90) - register as a publisher of all of the events we want to subscribe to avoid "module registering order" issue.

MODPATBLK-17 Register module as a publisher

---

src/main/java/org/folio/domain/Condition.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java

Resolves [MODPATBLK-20](https://issues.folio.org/browse/MODPATBLK-20).
All 6 blocks were only applied when the limit is exceeded. Instead, they should be also applied when the value is equal to the limit - otherwise the patron would be able to perform an extra action that should have been blocked.

MODPATBLK-20 Block when limit is reached

---

ramls/user.json
src/test/java/org/folio/rest/client/UsersClientTest.java

Resolves  [MODPATBLK-30](https://issues.folio.org/browse/MODPATBLK-30).
Allows `user` JSON schema to have additional fields.

MODPATBLK-30 Allow additional fields

---

descriptors/ModuleDescriptor-template.json
ramls/examples/user-summary.sample
ramls/user-summary.raml
ramls/userSummary.json
src/main/java/org/folio/domain/Condition.java
src/main/java/org/folio/exception/EntityNotFoundInDbException.java
src/main/java/org/folio/repository/UserSummaryRepository.java
src/main/java/org/folio/rest/impl/UserSummaryAPI.java
src/main/java/org/folio/service/UserSummaryService.java
src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java
src/test/java/org/folio/rest/impl/UserSummaryAPITest.java
src/test/java/org/folio/rest/utils/EntityBuilder.java

Recent tickets, such as [MODPATBLK-35](https://issues.folio.org/browse/MODPATBLK-35), [MODPATBLK-26](https://issues.folio.org/browse/MODPATBLK-26), require this diagnostic endpoint for developers to be able to fetch the underlying UserSummary object and quickly troubleshoot issues with automated patron blocks.

MODPATBLK-35 Add GET UserSummary endpoint

---

pom.xml
src/main/java/org/folio/domain/ActionBlocks.java
src/main/java/org/folio/domain/Condition.java
src/main/java/org/folio/repository/UserSummaryRepository.java
src/main/java/org/folio/service/PatronBlocksService.java
src/main/java/org/folio/util/UuidHelper.java
src/test/java/org/folio/domain/ActionBlocksTest.java
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java
src/test/java/org/folio/rest/utils/EntityBuilder.java

Resolves [MODPATBLK-34](https://issues.folio.org/browse/MODPATBLK-34).
Changes blocking by 'Maximum number of items charged out' condition - blocks borrowing when the limit is reached. 
All other blocks are enabled only when a limit is exceeded.

MODPATBLK-34 Limits for 3 implemented automated patron blocks not working properly

---

ramls/loan-policy.json
src/test/java/org/folio/rest/impl/AutomatedPatronBlocksAPITest.java

- update loan-policy json schema with new properties;
- remove additional properties restrictions;
Resolves: [MODPATBLK-83](https://issues.folio.org/browse/MODPATBLK-83)

MODPATBLK-83 Patron with 4 items checked out not being blocked on SNAPSHOT when limit set to 1 for patron group

---

descriptors/ModuleDescriptor-template.json

Resolves [MODPATBLK-85](https://issues.folio.org/browse/MODPATBLK-85).
There are issues with deploying mod-patron-blocks on the folio-testing environment because of missing pubsub permissions. The module is unable to register event types in pubsub.
From Okapi logs:
> 2021-03-10T03:22:41,674 INFO  DockerModuleHandle   mod-authtoken-2.8.0-SNAPSHOT.88 03:22:41 [165079/pubsub] [diku] [] [mod-authtoken] ERROR MainVerticle         Access requires permission: pubsub.event-types.post
> 2021-03-10T03:22:41,675 INFO  ProxyContext         165079/pubsub RES 403 5054us mod-authtoken-2.8.0-SNAPSHOT.88 http://10.36.1.62:9134/pubsub/event-types?
> 2021-03-10T03:22:41,676 INFO  DockerModuleHandle   mod-authtoken-2.8.0-SNAPSHOT.88 03:22:41 [353242/pubsub] [diku] [] [mod-authtoken] ERROR MainVerticle …

MODPATBLK-85 Add pubsub permissions to tenant API

---

src/main/java/org/folio/rest/impl/PatronBlockLimitsAPI.java
src/test/java/org/folio/rest/impl/PatronBlockLimitsAPITest.java
src/test/resources/patron-block-limits/limit_max_outstanding_feefine_balance_limit_out_of_range.json

Resolves [MODPATBLK-92](https://issues.folio.org/browse/MODPATBLK-92)
Limit for double values is changed from 9999.99 to 999999.99.

MODPATBLK-92 Change limit for double values

---

pom.xml

[MODPATBLK-106](https://issues.folio.org/browse/MODPATBLK-106)
Upgrade to RMB 33.1.3 which includes Log4j version with CVE-2021-44228 vulnerability fixed.

MODPATBLK-106 Upgrade to RMB 33.1.3 and Log4j 2.16.0

---

src/main/java/org/folio/service/PatronBlocksService.java

Skip unnecessary loan calls to improve performance. Test showed the same slow request can be improved from 12s to less than 300ms.

MODPATBLK-114 Cornell automated-patron-blocks performance issue

---

pom.xml

Add maven-failsafe-plugin to execute the integration test
src/test/java/org/folio/rest/ApiIT.java

MODPATBLK-121: Add maven-failsafe-plugin for ApiIT

---

src/main/java/org/folio/service/UserSummaryService.java
src/test/java/org/folio/service/UserSummaryServiceTest.java

Fix issue with automated patron blocks not disappearing after renewal of Aged to lost item 
- Updated UserSummary
- Added test
https://issues.folio.org/browse/MODPATBLK-126

MODPATBLK-126 "Aged to lost item" that is "Declared lost", then renewed is still counted towards 'Maximum number of lost items'

---

pom.xml

In the scope of the task on module upgrade, proper actions were fulfilled following instructions to upgrade RAML
Upgraded version of RMB to 34.0.0
https://issues.folio.org/browse/MODPATBLK-137

MODPATBLK-137 RMB v34 upgrade - Morning Glory 2022 R2 module release

---

pom.xml

Upgrade mod-pubsub-client from 2.3.0 to 2.6.1.
Upgrading mod-pubsub-client indirectly upgrades spring-beans from 5.2.8.RELEASE to 5.3.20 fixing Remote Code Execution https://nvd.nist.gov/vuln/detail/CVE-2022-22965
Upgrading mod-pubsub-client indirectly upgrades scala-library from 2.13.1 to 2.13.8 fixing Remote Code Execution (RCE) https://nvd.nist.gov/vuln/detail/CVE-2022-36944

MODPATBLK-144: mod-pubsub-client 2.6.1 fixing Remote Code Execution

---

src/test/java/org/folio/rest/TestBase.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java
src/test/java/org/folio/service/UserSummaryServiceTest.java

Run this on GitHub Actions ubuntu-latest:
```
mvn test -Dtest=SynchronizationAPITests
```
50% of all runs have this failure:
```
[ERROR]   SynchronizationAPITests.agedToLostEventShouldBeDeletedBeforeSynchronizationJobByUser:178
Expected: is <1>
but: was <0>
```
The API processes the aged-to-lost event asynchronously, it returns a 201 success without waiting for the event being stored to database: https://github.com/folio-org/mod-patron-blocks/blob/v1.7.0/src/main/java/org/folio/rest/impl/EventHandlersAPI.java#L88-L99
Therefore the test must wait until the event is in the database.
A similar issue:
```
[ERROR]   UserSummaryServiceTest.shouldAddEvent:55 Expected true
```

MODPATBLK-148: Sporadic test failures caused by async race condition

---

pom.xml

Upgrade mod-pubsub-client from Morning Glory version 2.6.1 to Nolana version 2.7.0.
The new mod-pubsub-client version no longer ships with org.scala-lang:scala-library and org.apache.kafka:kafka-clients that are not needed by mod-pubsub-client and by mod-patron-blocks. There were vulnerabilities in them: https://nvd.nist.gov/vuln/detail/CVE-2022-36944
https://nvd.nist.gov/vuln/detail/CVE-2022-34917
Upgrade Vert.x from 4.3.3 to 4.3.4.
Upgrade RMB from 35.0.0 to 35.0.1.
Upgrading RMB indirectly upgrades jackson-databind from 2.13.2.1 to 2.13.4 fixing Denial of Service (DoS): https://nvd.nist.gov/vuln/detail/CVE-2022-42004

MODPATBLK-149: Upgrade pubsub, RMB, Vert.x for Nolana

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
ramls/patron-block-conditions.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODPATBLK-159 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

Dockerfile
Jenkinsfile
pom.xml

Migrate module from Java 11 to Java 17. Resolves [MODPATBLK-166)](https://issues.folio.org/browse/MODPATBLK-166).
https://wiki.folio.org/display/TC/JDK+17+and+Java+17

[MODPATBLK-166] Migrate to Java 17

---

src/main/java/org/folio/service/LoanEventsGenerationService.java
src/test/java/org/folio/rest/impl/SynchronizationAPITests.java

Generate "Item aged to lost" events during synchronization.
[MODPATBLK-179](https://folio-org.atlassian.net/browse/MODPATBLK-179)
Add missing step to `LoanEventsGenerationService`

MODPATBLK-179 Generate ItemAgedToLostEvent during synchronization

---

descriptors/ModuleDescriptor-template.json
pom.xml

Remove permissions for event handlers. These permissions must be declared in mod-pubsub.
[MODPATBLK-195](https://folio-org.atlassian.net/browse/MODPATBLK-195)
_How does this change fulfill the purpose?_

MODPATBLK-195: Remove permissions for event handlers
